// Countries with a flag in public/flags (SVGs and names from the flag-icons project, MIT)
const COUNTRIES: Array<[code: string, name: string]> = [
  ["af", "Afghanistan"],
  ["ax", "Aland Islands"],
  ["al", "Albania"],
  ["dz", "Algeria"],
  ["as", "American Samoa"],
  ["ad", "Andorra"],
  ["ao", "Angola"],
  ["ai", "Anguilla"],
  ["aq", "Antarctica"],
  ["ag", "Antigua and Barbuda"],
  ["ar", "Argentina"],
  ["am", "Armenia"],
  ["aw", "Aruba"],
  ["au", "Australia"],
  ["at", "Austria"],
  ["az", "Azerbaijan"],
  ["bs", "Bahamas"],
  ["bh", "Bahrain"],
  ["bd", "Bangladesh"],
  ["bb", "Barbados"],
  ["by", "Belarus"],
  ["be", "Belgium"],
  ["bz", "Belize"],
  ["bj", "Benin"],
  ["bm", "Bermuda"],
  ["bt", "Bhutan"],
  ["bo", "Bolivia"],
  ["bq", "Bonaire, Sint Eustatius and Saba"],
  ["ba", "Bosnia and Herzegovina"],
  ["bw", "Botswana"],
  ["bv", "Bouvet Island"],
  ["br", "Brazil"],
  ["io", "British Indian Ocean Territory"],
  ["bn", "Brunei Darussalam"],
  ["bg", "Bulgaria"],
  ["bf", "Burkina Faso"],
  ["bi", "Burundi"],
  ["cv", "Cabo Verde"],
  ["kh", "Cambodia"],
  ["cm", "Cameroon"],
  ["ca", "Canada"],
  ["ky", "Cayman Islands"],
  ["cf", "Central African Republic"],
  ["td", "Chad"],
  ["cl", "Chile"],
  ["cn", "China"],
  ["cx", "Christmas Island"],
  ["cc", "Cocos (Keeling) Islands"],
  ["co", "Colombia"],
  ["km", "Comoros"],
  ["ck", "Cook Islands"],
  ["cr", "Costa Rica"],
  ["hr", "Croatia"],
  ["cu", "Cuba"],
  ["cw", "Curaçao"],
  ["cy", "Cyprus"],
  ["cz", "Czech Republic"],
  ["ci", "Côte d'Ivoire"],
  ["cd", "Democratic Republic of the Congo"],
  ["dk", "Denmark"],
  ["dj", "Djibouti"],
  ["dm", "Dominica"],
  ["do", "Dominican Republic"],
  ["ec", "Ecuador"],
  ["eg", "Egypt"],
  ["sv", "El Salvador"],
  ["gq", "Equatorial Guinea"],
  ["er", "Eritrea"],
  ["ee", "Estonia"],
  ["sz", "Eswatini"],
  ["et", "Ethiopia"],
  ["fk", "Falkland Islands"],
  ["fo", "Faroe Islands"],
  ["fm", "Federated States of Micronesia"],
  ["fj", "Fiji"],
  ["fi", "Finland"],
  ["fr", "France"],
  ["gf", "French Guiana"],
  ["pf", "French Polynesia"],
  ["tf", "French Southern Territories"],
  ["ga", "Gabon"],
  ["gm", "Gambia"],
  ["ge", "Georgia"],
  ["de", "Germany"],
  ["gh", "Ghana"],
  ["gi", "Gibraltar"],
  ["gr", "Greece"],
  ["gl", "Greenland"],
  ["gd", "Grenada"],
  ["gp", "Guadeloupe"],
  ["gu", "Guam"],
  ["gt", "Guatemala"],
  ["gg", "Guernsey"],
  ["gn", "Guinea"],
  ["gw", "Guinea-Bissau"],
  ["gy", "Guyana"],
  ["ht", "Haiti"],
  ["hm", "Heard Island and McDonald Islands"],
  ["va", "Holy See"],
  ["hn", "Honduras"],
  ["hk", "Hong Kong"],
  ["hu", "Hungary"],
  ["is", "Iceland"],
  ["in", "India"],
  ["id", "Indonesia"],
  ["ir", "Iran"],
  ["iq", "Iraq"],
  ["ie", "Ireland"],
  ["im", "Isle of Man"],
  ["il", "Israel"],
  ["it", "Italy"],
  ["jm", "Jamaica"],
  ["jp", "Japan"],
  ["je", "Jersey"],
  ["jo", "Jordan"],
  ["kz", "Kazakhstan"],
  ["ke", "Kenya"],
  ["ki", "Kiribati"],
  ["kw", "Kuwait"],
  ["kg", "Kyrgyzstan"],
  ["la", "Laos"],
  ["lv", "Latvia"],
  ["lb", "Lebanon"],
  ["ls", "Lesotho"],
  ["lr", "Liberia"],
  ["ly", "Libya"],
  ["li", "Liechtenstein"],
  ["lt", "Lithuania"],
  ["lu", "Luxembourg"],
  ["mo", "Macau"],
  ["mg", "Madagascar"],
  ["mw", "Malawi"],
  ["my", "Malaysia"],
  ["mv", "Maldives"],
  ["ml", "Mali"],
  ["mt", "Malta"],
  ["mh", "Marshall Islands"],
  ["mq", "Martinique"],
  ["mr", "Mauritania"],
  ["mu", "Mauritius"],
  ["yt", "Mayotte"],
  ["mx", "Mexico"],
  ["md", "Moldova"],
  ["mc", "Monaco"],
  ["mn", "Mongolia"],
  ["me", "Montenegro"],
  ["ms", "Montserrat"],
  ["ma", "Morocco"],
  ["mz", "Mozambique"],
  ["mm", "Myanmar"],
  ["na", "Namibia"],
  ["nr", "Nauru"],
  ["np", "Nepal"],
  ["nl", "Netherlands"],
  ["nc", "New Caledonia"],
  ["nz", "New Zealand"],
  ["ni", "Nicaragua"],
  ["ne", "Niger"],
  ["ng", "Nigeria"],
  ["nu", "Niue"],
  ["nf", "Norfolk Island"],
  ["kp", "North Korea"],
  ["mk", "North Macedonia"],
  ["mp", "Northern Mariana Islands"],
  ["no", "Norway"],
  ["om", "Oman"],
  ["pk", "Pakistan"],
  ["pw", "Palau"],
  ["pa", "Panama"],
  ["pg", "Papua New Guinea"],
  ["py", "Paraguay"],
  ["pe", "Peru"],
  ["ph", "Philippines"],
  ["pn", "Pitcairn"],
  ["pl", "Poland"],
  ["pt", "Portugal"],
  ["pr", "Puerto Rico"],
  ["qa", "Qatar"],
  ["cg", "Republic of the Congo"],
  ["ro", "Romania"],
  ["ru", "Russia"],
  ["rw", "Rwanda"],
  ["re", "Réunion"],
  ["bl", "Saint Barthélemy"],
  ["sh", "Saint Helena, Ascension and Tristan da Cunha"],
  ["kn", "Saint Kitts and Nevis"],
  ["lc", "Saint Lucia"],
  ["mf", "Saint Martin"],
  ["pm", "Saint Pierre and Miquelon"],
  ["vc", "Saint Vincent and the Grenadines"],
  ["ws", "Samoa"],
  ["sm", "San Marino"],
  ["st", "Sao Tome and Principe"],
  ["sa", "Saudi Arabia"],
  ["sn", "Senegal"],
  ["rs", "Serbia"],
  ["sc", "Seychelles"],
  ["sl", "Sierra Leone"],
  ["sg", "Singapore"],
  ["sx", "Sint Maarten"],
  ["sk", "Slovakia"],
  ["si", "Slovenia"],
  ["sb", "Solomon Islands"],
  ["so", "Somalia"],
  ["za", "South Africa"],
  ["gs", "South Georgia and the South Sandwich Islands"],
  ["kr", "South Korea"],
  ["ss", "South Sudan"],
  ["es", "Spain"],
  ["lk", "Sri Lanka"],
  ["ps", "State of Palestine"],
  ["sd", "Sudan"],
  ["sr", "Suriname"],
  ["sj", "Svalbard and Jan Mayen"],
  ["se", "Sweden"],
  ["ch", "Switzerland"],
  ["sy", "Syria"],
  ["tw", "Taiwan"],
  ["tj", "Tajikistan"],
  ["tz", "Tanzania"],
  ["th", "Thailand"],
  ["tl", "Timor-Leste"],
  ["tg", "Togo"],
  ["tk", "Tokelau"],
  ["to", "Tonga"],
  ["tt", "Trinidad and Tobago"],
  ["tn", "Tunisia"],
  ["tm", "Turkmenistan"],
  ["tc", "Turks and Caicos Islands"],
  ["tv", "Tuvalu"],
  ["tr", "Türkiye"],
  ["ug", "Uganda"],
  ["ua", "Ukraine"],
  ["ae", "United Arab Emirates"],
  ["gb", "United Kingdom"],
  ["um", "United States Minor Outlying Islands"],
  ["us", "United States of America"],
  ["uy", "Uruguay"],
  ["uz", "Uzbekistan"],
  ["vu", "Vanuatu"],
  ["ve", "Venezuela"],
  ["vn", "Vietnam"],
  ["vg", "Virgin Islands (British)"],
  ["vi", "Virgin Islands (U.S.)"],
  ["wf", "Wallis and Futuna"],
  ["eh", "Western Sahara"],
  ["ye", "Yemen"],
  ["zm", "Zambia"],
  ["zw", "Zimbabwe"],
]

const NAME_BY_CODE = new Map(COUNTRIES)

// Countries offered when setting a flag by hand; all others arrive via trackmania.io
const SELECTABLE: Array<{ code: string; name: string }> = [
  { code: "de", name: "Deutschland" },
  { code: "at", name: "Österreich" },
]

// Compare names without case, accents and punctuation ("Réunion" = "reunion")
function normalizeName(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
}

// Spellings used by trackmania.io that differ from the list above (keys are normalised)
const ALIASES: Record<string, string> = {
  "united states": "us",
  usa: "us",
  turkey: "tr",
  czechia: "cz",
  "korea, republic of": "kr",
  "russian federation": "ru",
  macedonia: "mk",
  "ivory coast": "ci",
  "cote d ivoire": "ci",
  "great britain": "gb",
  "viet nam": "vn",
  "republic of moldova": "md",
  "the netherlands": "nl",
  "united arab emirates": "ae",
  "hong kong": "hk",
  taiwan: "tw",
  "bosnia herzegovina": "ba",
  brunei: "bn",
  "cape verde": "cv",
  palestine: "ps",
  macao: "mo",
  swaziland: "sz",
  "east timor": "tl",
  vatican: "va",
  "vatican city": "va",
  congo: "cg",
  "democratic republic of the congo": "cd",
  "dr congo": "cd",
  laos: "la",
  syria: "sy",
  iran: "ir",
  bolivia: "bo",
  venezuela: "ve",
  tanzania: "tz",
  moldova: "md",
  "north korea": "kp",
  korea: "kr",
  uk: "gb",
  england: "gb",
  scotland: "gb",
  wales: "gb",
  "northern ireland": "gb",
}

export function isCountryCode(code: string): boolean {
  return NAME_BY_CODE.has(code)
}

export function countryName(code: string): string {
  return SELECTABLE.find((c) => c.code === code)?.name ?? NAME_BY_CODE.get(code) ?? code.toUpperCase()
}

// The short manual list, plus the given country if it is set to something else
export function countryOptions(current?: string | null): Array<{ code: string; name: string }> {
  if (!current || SELECTABLE.some((c) => c.code === current)) return SELECTABLE
  return [...SELECTABLE, { code: current, name: countryName(current) }]
}

// Country code for an English country name, or null if it is unknown
export function countryCodeByName(name: string): string | null {
  const key = normalizeName(name)
  if (ALIASES[key]) return ALIASES[key]
  return COUNTRIES.find(([, n]) => normalizeName(n) === key)?.[0] ?? null
}
